#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 25 17:21:03 2017

@author: brendontucker

from Billy-yoyo
"""

import functools

def campusCup(emails):
    scores = {}
    for email in emails:
        domain = email.split("@")[-1]
        if domain not in scores:
            scores[domain] = 0
        scores[domain] += 20
    convert = lambda x: (0, 300, 800, 1500, 1500, 2500)[scores[x]//100]
    scores = {x:convert(x) for x in scores}
    print(scores)
    
    results = sorted(scores.keys(), key = lambda x: scores[x] - len(x), reverse = True)
    return results