#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 25 17:18:57 2017

@author: brendontucker

from CHMELEVSKIJ

"""

from collections import Counter

def campusCup(emails):
    unis = [email.split('@')[1] for email in emails]
    unis_count = Counter(unis)
    
    unis_0 = sorted([uni[0] for uni in unis_count.most_common() if uni[1] < 5])
    unis_100 = sorted([uni[0] for uni in unis_count.most_common() if (uni[1] >= 5 and uni[1] < 10)])
    unis_200 = sorted([uni[0] for uni in unis_count.most_common() if (uni[1] >= 10 and uni[1] < 15)])
    unis_300 = sorted([uni[0] for uni in unis_count.most_common() if (uni[1] >= 15 and uni[1] < 25)])
    unis_500 = sorted([uni[0] for uni in unis_count.most_common() if uni[1] >= 25])
    
    return unis_500 + unis_300 + unis_200 + unis_100 + unis_0