#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 15 12:52:06 2017

@author: brendontucker
"""

network = [[0, 2, 4, 8, 0, 0],
           [0, 0, 0, 9, 0, 0],
           [0, 0, 0, 0, 0, 10],
           [0, 0, 6, 0, 0, 10],
           [10, 10, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0]]
           
resource = 4
server = 5

for x in network[resource]: 