#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 13 09:57:45 2016

@author: brendontucker
"""

jobs = [15, 30, 15, 5, 10] 
servers = 3
length = servers - 1

jobs.sort(reverse = True) 

#output Matrix
serverMatrix = [[0 for y in range(1)] for x in range(servers)]

serverLengthMatrix = [[0 for y in range(1)] for x in range(servers)]

#conditional entry length stuff here--special cases 0 1 ect
'''
for x in range(servers):
    serverMatrix[x][0] = x
    serverLengthMatrix[x][0] = jobs[x]
'''
for x in jobs:
    position = serverLengthMatrix.index(min(serverLengthMatrix))
    serverMatrix[position].append(position)    
    serverLengthMatrix[position][0] = serverLengthMatrix[position][0] + x
    
    







    