#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 15 11:47:09 2016

@author: brendontucker
"""

timestamp = [1450625399, 1450625400, 1450625500, 1450625550, 
             1451644200, 1451690100, 1451691000]

instrument = ["HPQ", 
 "HPQ", 
 "HPQ", 
 "HPQ", 
 "AAPL", 
 "HPQ", 
 "GOOG"]
side = ["sell", 
 "buy", 
 "buy", 
 "sell", 
 "buy", 
 "buy", 
 "buy"]
price = [10, 20.3, 35.5, 8.65, 20, 10, 100.35]
size = [10, 1, 2, 3, 5, 1, 10]

expected_output = [["2015-12-20","HPQ","10.00","35.50","8.65","8.65"], 
 ["2016-01-01","AAPL","20.00","20.00","20.00","20.00"], 
 ["2016-01-01","GOOG","100.35","100.35","100.35","100.35"], 
 ["2016-01-01","HPQ","10.00","10.00","10.00","10.00"]]
 
import datetime
#convert unix time
timeList =[]
for x in timestamp:
    timeList.append(datetime.datetime.fromtimestamp((x)).strftime('%Y-%m-%d'))

length1 = len(timeList)
checkCounter = 0
incCounter = 1

timeList2 = list()
for x in timeList:
    timeList2.append(x)
#find unique times
while checkCounter < len(timeList):
    while incCounter < len(timeList):
        if timeList[checkCounter] == timeList[incCounter]:
            timeList.remove(timeList[incCounter])
            incCounter = incCounter
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
    incCounter = 0
    incCounter = checkCounter + 1
#organize indexes of unique times
timeList3 = [[] for x in range(len(timeList))]
incCounter = 0 
checkCounter = 0
while checkCounter < len(timeList):
    incCounter = 0
    while incCounter < len(timeList2):
        if timeList[checkCounter] == timeList2[incCounter]:
            timeList3[checkCounter].append(incCounter)
            incCounter = incCounter + 1
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
        #where is teh restart value?

instrumentList = list()
for x in instrument:
    instrumentList.append(x)

checkCounter = 0
incCounter = 1

while checkCounter < len(instrumentList):
    while incCounter < len(instrumentList):
        if instrumentList[checkCounter] == instrumentList[incCounter]:
            instrumentList.remove(instrumentList[incCounter])
            incCounter = incCounter
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
    incCounter = 0
    incCounter = checkCounter + 1           

instrumentList2 = [[] for x in range(len(instrumentList))]

incCounter = 0 
checkCounter = 0
while checkCounter < len(instrumentList):
    incCounter = 0
    while incCounter < len(instrument):
        if instrumentList[checkCounter] == instrument[incCounter]:
            instrumentList2[checkCounter].append(incCounter)
            incCounter = incCounter + 1
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
    
checkCounter = 0
incCounter = 0
listChecker = 0
timeCounter = 0
appendPos = 0 #where to append instrument/time independent entries
outputList = [[] for x in range(length1)]
instrumentList2.sort()
timeList3.sort()
while checkCounter < len(instrumentList2):
    if len(instrumentList2[checkCounter]) == 1:
        outputList[appendPos].append(instrumentList2[checkCounter][0])
        checkCounter = checkCounter + 1
        appendPos = appendPos + 1
    elif len(instrumentList2[checkCounter]) > 1:
        incCounter = 0
        listChecker = 0
        timeCounter = 0
        while incCounter < len(instrumentList2[checkCounter]):
            timeCounter = 0
            while timeCounter < len(timeList3[listChecker]):
                if instrumentList2[checkCounter][incCounter] == timeList3[listChecker][timeCounter]:
                    outputList[appendPos].append(instrumentList2[checkCounter][incCounter])
                    break
                else:
                    timeCounter = timeCounter + 1
            incCounter = incCounter + 1
            listChecker = listChecker + 1
            appendPos = appendPos + 1
        
    checkCounter = checkCounter + 1
        #thehard part...
#
    
#timeList3 and instrumentList2, need to find where these two intersect.

            
#why didn't this work?
'''    
while incCounter < len(instrumentList2[checkCounter]):
    if instrumentList2[checkCounter][incCounter] in timeList3[listChecker]: 
        outputList[appendPos].append(instrumentList2[checkCounter][incCounter])
        incCounter = incCounter + 1 
    else:
        listChecker = listChecker + 1
        appendPos = appendPos + 1    
''' 