#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 21 08:41:01 2016

@author: brendontucker
"""

timestamp = [801840015, 1346505615, 1346505615, 1346505615, 1346505615, 
             1346516000, 1592632799, 1592632799, 1592669600, 1592669600]

instrument = ["LAG", 
 "HPQ", 
 "HPQ", 
 "HPQ", 
 "AAOL", 
 "LAG", 
 "LAG", 
 "GOOG", 
 "AAOL", 
 "HPQ"]
side = ["sell", 
 "sell", 
 "buy", 
 "sell", 
 "sell", 
 "buy", 
 "sell", 
 "sell", 
 "buy", 
 "sell"]
price = [50.4, 75.64, 42.62, 92.69, 48.53, 20.85, 61.33, 32.61, 36.53, 28.74]
size = [543, 448, 140, 889, 857, 270, 305, 115, 243, 450]

expected_output = [["1995-05-30","LAG","50.40","50.40","50.40","50.40"], 
 ["2012-09-01","AAOL","48.53","48.53","48.53","48.53"], 
 ["2012-09-01","HPQ","75.64","92.69","42.62","92.69"], 
 ["2012-09-01","LAG","20.85","20.85","20.85","20.85"], 
 ["2020-06-20","AAOL","36.53","36.53","36.53","36.53"], 
 ["2020-06-20","GOOG","32.61","32.61","32.61","32.61"], 
 ["2020-06-20","HPQ","28.74","28.74","28.74","28.74"], 
 ["2020-06-20","LAG","61.33","61.33","61.33","61.33"]]
 
import datetime
#convert unix time
timeList =[]
for x in timestamp:
    timeList.append(datetime.datetime.fromtimestamp((x)).strftime('%Y-%m-%d'))

length1 = len(timeList)
checkCounter = 0
incCounter = 1
#copy of timeList
timeList2 = list()
for x in timeList:
    timeList2.append(x)

#find unique times
while checkCounter < len(timeList):
    while incCounter < len(timeList):
        if timeList[checkCounter] == timeList[incCounter]:
            timeList.remove(timeList[incCounter])
            incCounter = incCounter
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
    incCounter = 0
    incCounter = checkCounter + 1

#organize indexes of unique times
timeList3 = [[] for x in range(len(timeList))]
incCounter = 0 
checkCounter = 0
while checkCounter < len(timeList):
    incCounter = 0
    while incCounter < len(timeList2):
        if timeList[checkCounter] == timeList2[incCounter]:
            timeList3[checkCounter].append(incCounter)
            incCounter = incCounter + 1
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
        #where is teh restart value?

instrumentList = list()
for x in instrument:
    instrumentList.append(x)

checkCounter = 0
incCounter = 1
#creates a list of all unique instruments 
#creation of extra data as an effort to not touch input data and easier prototyping
#maybe alter original instrument list if memory demands still too high and time limit
#exceeded
instrumentList.sort()
#why did I have to sort!? v confusing... need to investigate further in future
while checkCounter < len(instrumentList):
    while incCounter < len(instrumentList):
        if instrumentList[checkCounter] == instrumentList[incCounter]:
            instrumentList.remove(instrumentList[incCounter])
            incCounter = incCounter
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1
    incCounter = 0
    incCounter = checkCounter + 1           

instrumentList2 = [[] for x in range(len(instrumentList))]

incCounter = 0 
checkCounter = 0
while checkCounter < len(instrumentList):
    incCounter = 0
    while incCounter < len(instrument):
        if instrumentList[checkCounter] == instrument[incCounter]:
            instrumentList2[checkCounter].append(incCounter)
            incCounter = incCounter + 1
        else:
            incCounter = incCounter + 1
    checkCounter = checkCounter + 1

checkCounter = 0
incCounter = 0
listChecker = 0
timeCounter = 0
appendPos = 0 #where to append instrument/time independent entries
outputList = [[] for x in range(length1)]
#instrumentList2.sort()
#timeList3.sort()
while checkCounter < len(instrumentList2):
    if len(instrumentList2[checkCounter]) == 1:
        outputList[appendPos].append(instrumentList2[checkCounter][0])
        appendPos = appendPos + 1
    elif len(instrumentList2[checkCounter]) > 1:
        incCounter = 0
        listChecker = 0
        timeCounter = 0
        while incCounter < len(instrumentList2[checkCounter]):
            if instrumentList2[checkCounter][incCounter] in timeList3[listChecker]: 
                outputList[appendPos].append(instrumentList2[checkCounter][incCounter])
                incCounter = incCounter + 1 
            else:
                listChecker = listChecker + 1
                if outputList[appendPos] == []:
                    appendPos = appendPos
                else:
                    appendPos = appendPos + 1
        appendPos = appendPos + 1 #once inc spills over, new instrument is being looked
        #at, so app must incerase 
        
    checkCounter = checkCounter + 1

#outputList.sort()    

incCounter = 0 #just using to delete now
while incCounter < len(outputList):
    if outputList[incCounter] == []:
        outputList.remove(outputList[incCounter])
        incCounter = incCounter
    else:
        incCounter = incCounter + 1

counter = 0
counter2 = 0        
while counter < len(outputList):
   if outputList[counter][0] 