#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 07:08:17 2017

@author: brendontucker
"""

a = [24, 85, 0]

a.reverse()

for x in a:
    a[a.index(x)] =format(x, '#010b')
    
for x in a:
    a[a.index(x)] = x[2:]
      
finalBin = ''.join(a)

ans = int(finalBin, 2)