#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 12 10:07:37 2016

Doesn't work yet and not sure if it will even be any quicker... may need a 
totally new design

@author: brendontucker
"""

\
n = 6
roads = [[0,4], 
 [5,0], 
 [2,1], 
 [1,4], 
 [2,3], 
 [5,2]]

boo1 = True
list1 = list()
length = n - 1
roadLength = len(roads)
counter1 = 0
while counter1 <= length:
    list1.append(counter1)
    counter1 = counter1 + 1

pos1 = 0
pos2 = 1
counter1 = 0
counter2 = 0
connectValue = None
connectList = list()
connectList2 = list()
counter4 = 0
counter5 = 1
counter6 = 0
length2 = len(connectList) - 1


while counter2 <= length: #should be this [while counter2 <= length:]
    connectList = list()
    counter1 = 0
    while counter1 < roadLength:
        if roads[counter1][pos1] == counter2: 
            connectValue = roads[counter1][pos2]
            connectList.append(connectValue)
            counter1 = counter1 + 1
        elif roads[counter1][pos2] == counter2:
            connectValue = roads[counter1][pos1]
            connectList.append(connectValue)
            counter1 = counter1 + 1
        else:
            counter1 = counter1 + 1
    
    counter4 = 0
    length2 = len(connectList) - 1
    connectList.sort()
    connectList2 = list()
    while counter4 <= length2: 
        counter3 = 0
        connectValue2 = None
        while counter3 < roadLength: 
            if roads[counter3][pos1] == connectList[counter4]: 
                connectValue2 = roads[counter3][pos2]
                if len(connectList2) > 0:
                    connectLength = len(connectList2)
                    connectCounter = 0
                    while connectCounter < connectLength:
                        if connectList2[connectCounter] == connectValue2:
                            counter3 = counter3 + 1
                            break
                        else:
                            connectCounter = connectCounter + 1
                    connectList2.append(connectValue2)
                    counter3 = counter3 + 1
                else:        
                    connectList2.append(connectValue2)
                    counter3 = counter3 + 1
            elif roads[counter3][pos2] == connectList[counter4]:
                connectValue2 = roads[counter3][pos1]
                connectList2.append(connectValue2)
                counter3 = counter3 + 1
            else:
                counter3 = counter3 + 1
    
        counter4 = counter4 + 1

    connectList3 = list()
    connectList3 = connectList2 + connectList
    connectList3.sort()
    #have to delete repeats here too?
    counter5 = 1
    counter6 = 0
    
    while counter6 <= len(connectList3): #entry 0 has to be unique by def
        while counter5 <= len(connectList3) - 1:
            if connectList3[counter5] == connectList3[counter6]:
                connectList3.remove(connectList3[counter5])
                counter5 = counter5
            else:
                counter5 = counter5 + 1
        counter6 = counter6 + 1
        counter5 = 0
        counter5 = counter6 + 1
    
    boo2 = bool
    boo2 = connectList3 == list1
    if boo1 == boo2:
        counter2 = counter2 + 1
    else:
        break
