#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 30 18:35:05 2017

@author: brendontucker

feel like generating binary numbers should easily be a recursive problem...

jk jk these are all covered by built in functions
"""

n = 37

binaryN = list(bin(n))
binaryN = binaryN[2:]