#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 07:53:48 2017

@author: brendontucker
"""

a = 97

a = list(bin(a))
a = a[2:]
a = a[::-1]
ab = ''.join(a)
reversedBin = int(ab, 2)