#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan  2 07:30:11 2017

this is just algorithmically ugly... 

doesnt pass some hidden tests... likely times out. Need to refactor

@author: brendontucker
"""

roads = [[7,9,17], 
 [13,11,19], 
 [4,9,8], 
 [7,6,14], 
 [5,6,9], 
 [1,7,1], 
 [5,9,15], 
 [5,4,13], 
 [6,0,0], 
 [6,2,6], 
 [10,8,18], 
 [4,8,11], 
 [3,9,12], 
 [7,3,10], 
 [6,10,16], 
 [8,3,7], 
 [0,8,2], 
 [3,4,5], 
 [2,9,4], 
 [4,1,3]]
        
counter = 0
counter2 = 0
boo1 = True


while counter < len(roads): #len(roads)
    value1 = roads[counter][0]
    value2 = roads[counter][1]
    checkValue1 = roads[counter][2] - 1
    checkValue2 = roads[counter][2] + 1
    counter2 = 0
    while counter2 < len(roads): #len(roads)
        if counter2 == counter:
            counter2 = counter2 + 1
        elif value1 in roads[counter2][:2] :
            if checkValue1 <= roads[counter2][2] <= checkValue2:
                boo1 = False
                counter2 = counter2 + 1
            else: #think this is wrong...
                break #this passed extra tests
        elif value2 in roads[counter2][:2] :
            if checkValue1 <= roads[counter2][2] <= checkValue2:
                boo1 = False
                counter2 = counter2 + 1
            else: #only one test left to pass
                break
        else:
            counter2 = counter2 + 1
    if boo1 == False:
        break
    else:
        counter = counter + 1
    






'''
while counter < len(roads):
    value1 = roads[counter][0]
    value2 = roads[counter][1]
    checkValue1 = roads[counter][2] - 1
    checkValue2 = roads[counter][2] + 1
    while counter2 < len(roads):
        if roads[counter2] == value1 or roads[counter2] == value2        
'''

        