#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan  2 07:30:11 2017

this is just algorithmically ugly... 

@author: brendontucker
"""

roads = [[0, 1, 0],
         [4, 1, 2],
         [4, 3, 4],
         [2, 3, 1],
         [2, 0, 3]]
        
counter = 0
counter2 = 0
boo1 = True


while counter < 1: #len(roads)
    value1 = roads[counter][0]
    value2 = roads[counter][1]
    checkValue1 = roads[counter][2] - 1
    checkValue2 = roads[counter][2] + 1
    while counter2 < len(roads):
        if value1 in roads[counter2][:2] :
            if checkValue1 <= roads[counter2][2] <= checkValue2:
                boo1 = False
                counter2 = counter2 + 1
            else:
                if value2 in roads[counter2][:2] :
                    if checkValue1 <= roads[counter2][2] <= checkValue2:
                        boo1 = False
                        counter2 = counter2 + 1
                    else:
                        counter2 = counter2 + 1
        else:
            counter2 = counter2 + 1
    if boo1 == False:
        break
    else:
        counter = counter + 1
    






'''
while counter < len(roads):
    value1 = roads[counter][0]
    value2 = roads[counter][1]
    checkValue1 = roads[counter][2] - 1
    checkValue2 = roads[counter][2] + 1
    while counter2 < len(roads):
        if roads[counter2] == value1 or roads[counter2] == value2        
'''

        