#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 07:37:12 2017

@author: brendontucker
"""

a = 2
b = 3
diff = b - a #need to account for when diff == 0 

counter = 0
numlist = []
if diff > 0:
    while counter <= diff:
        numlist.append(a + counter)
        counter += 1
else:
    numlist[0] = a
    numlist[1] = b

for x in numlist:
    numlist[numlist.index(x)] =format(x, '#010b')
    
for x in numlist:    
    numlist[numlist.index(x)] = x[2:]

counter = 0
for x in numlist:
    for y in x:
        if y == '1':
            counter += 1
            