#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan  4 08:05:22 2017

@author: brendontucker
"""
n = 3
k = 2

dp = [1]
for i in range(1, k):
    dp.append(0)
for i in range(n):
    sum = dp[0]
    j = k - 1
    while j > 0:
        sum += dp[j]
        dp[j] = dp[j - 1]
        j -= 1
    dp[0] = sum
