#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  7 09:40:24 2017

@author: brendontucker
"""

inputArray = [3, 6, -2, -5, 7, 3]

left = 0
right = 1
temp = 0
ans = 0
length = len(inputArray)

while right < length: #length - 1
    temp = inputArray[right] * inputArray[left] 
    if right == 1: #this catches the case of all negative entries in an array 
        ans = temp
    elif temp >= ans:
        ans = temp
    else:
        ans = ans
    
    right = right + 1
    left = left + 1
    