#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  8 08:14:17 2017

@author: brendontucker
"""

inputArray = ["aba", "aa", "ad", "vcd", "aba"]


temp = 0
largest = 0
for x in inputArray:
    temp = len(x)
    if temp > largest:
        largest = temp

list1 = list()

for x in inputArray:
    if len(x) == largest:
        list1.append(x)        