#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  5 11:36:41 2017

@author: brendontucker
"""

year = 70


century = (year / 100)
century2 = year // 100

if century < 1.0:
    century = 1

elif (century / century2) == 1.0:
    century = int(century)

else:
    century = (year // 100) + 1

    