#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  7 09:23:18 2017

@author: brendontucker
"""

inputString = "aabaa"


boo = False
inputString2 = inputString[::-1]

if inputString == inputString2:
    boo = True