#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  9 09:48:40 2017

@author: brendontucker
"""

n = 1230

luckBool = False

nList = list(str(n))

length = len(nList)

halfSpot = (length // 2) - 1

firstHalf = nList[:halfSpot + 1] 
secondHalf = nList[halfSpot +1:]

firstSum = 0
secondSum = 0

for x in firstHalf:
    firstSum += int(x)

for x in secondHalf:
    secondSum += int(x)
    
if firstSum == secondSum:
    luckBool = True
else:
    luckBool = False


