#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 10 12:08:36 2017

@author: brendontucker
"""

s = "this(is)Python(example)test" #"Code(Cha(lle)nge)"

expectedOutput = "CodeegnlleahC"

length = len(s)

half = length // 2

paraCounter = 0 

for x in s:
    if x == '(':
        paraCounter += 1

        
prePara = list()

#creates portion of word that has no reverse applied at the begining
#might be harder to find Python in... "xxx(dd)Python(dd)xxxx"
for x in s:
    if x != '(':
        prePara.append(x)
    elif x == '(':
        break
    
# find inner sections
#max inner sections limited to number of parenthases

innerContent = [[] for x in range(paraCounter - 1)] #should be paraCounter -1
                       
closed1 = 0
closed2 = 0

innerCounter = 0
innerPos = 0
#put this all in a {while innerPos < len(innerContent)} ??
while innerCounter < len(s):
    if s[innerCounter] == ')':
        closed1 = innerCounter
        innerCounter += 1
        while innerCounter < len(s):
            if s[innerCounter] == '(':
                closed2 = innerCounter
                innerContent[innerPos] = s[closed1 + 1:closed2]
                innerPos += 1
                break
            else:
                innerCounter += 1
        
    else:
        innerCounter += 1        

#count parenthases
#determine innermost

sList = list(s)

 
newS = [[] for x in range(paraCounter)]
