#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 13 11:56:33 2017

@author: brendontucker
"""

s = "Code(Cha(lle)nge)"
#s = 'pre(inner(bracket)test(because)need)post'
sList = list(s)
expectedOutput = "CodeegnlleahC"

length = len(s)

half = length // 2

paraCounter = 0 

for x in s:
    if x == '(':
        paraCounter += 1

        
prePara = list()

#creates portion of word that has no reverse applied at the begining
#might be harder to find Python in... "xxx(dd)Python(dd)xxxx"
closed1 = 0
closed2 = 0

preCounter = 0

while preCounter < len(s):
    if sList[preCounter] == '(':
        closed2 = preCounter
        prePara = sList[closed1:closed2]
        break
    else:
        preCounter += 1

   
# find inner sections
#max inner sections limited to number of parenthases

innerContent = [[] for x in range(paraCounter - 1)] #should be paraCounter -1
                       
closed1 = 0
closed2 = 0

innerCounter = 0
innerPos = 0
#put this all in a {while innerPos < len(innerContent)} ??
#Don't actually think I need this for the new list method
while innerCounter < len(sList):
    if sList[innerCounter] == ')':
        closed1 = innerCounter
        innerCounter += 1
        while innerCounter < len(sList):
            if sList[innerCounter] == '(':
                closed2 = innerCounter
                innerContent[innerPos] = sList[closed1 + 1:closed2]
                innerPos += 1
                break
            else:
                innerCounter += 1
        
    else:
        innerCounter += 1        

#count parenthases
#determine innermost

#sList = list(s)
newSNeed = 1 + ((paraCounter - 1) * 2)
 
newS = [[] for x in range(newSNeed)]

newSCounter = 0
leftPara = 0
leftPos = [[]for x in range((paraCounter // 2) + 1)]



#find para positions?
while newSCounter < len(sList):
    if sList[newSCounter] == '(':
        leftPos[leftPara] = newSCounter
        leftPara =+ 1
        newSCounter += 1
    else:
        newSCounter += 1 
              
    
newSPos = 0
rightPara = 0
rightPos = [[]for x in range((paraCounter // 2) + 1)]


while newSCounter < len(sList):
    if sList[newSCounter] == ')':
        rightPos[rightPara] = newSCounter
        rightPara =+ 1
        newSCounter += 1
    else:
        newSCounter += 1



'''
while newSCounter < 3:#len(sList):
    if sList[newSCounter] == '(' or ')':
        newSCounter += 1
        if sList[newSCounter] != '(' or ')':
            newS[newSPos].append(sList[newSCounter])
            newSCounter += 1
        else:
            newSPos += 1
            break
    else:
        newSCounter += 1
'''




'''
#might need to switch to list methods...
#could use regex here
while newSCounter < len(sList):
    if sList[newSCounter] == '(' or ')':
        closed1 = newSCounter
        newSCounter += 1
        while newSCounter < len(sList):  #need an if here for finding a '(' before ')'
            if s[newSCounter] == ')' or '(':
                closed2 = newSCounter
                newS[newSPos] = sList[closed1 + 1:closed2]
                newSPos += 1
                break
            else:
                newSCounter += 1
    else:
        newSCounter += 1
'''       