#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  7 10:42:37 2017

@author: brendontucker
"""

n = 3

area = 0
m = 1


while m <= n:
    if m == 1:
        area = 1
    else:
        growth = 4 * (m - 1)
        area = area + growth #might need starter logic for when m = 1
        
    m = m + 1