#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  9 12:06:32 2017

@author: brendontucker
"""

#could just check non negative elements and see if they need to be switched 

a = [-1, 150, 190, 170, -1, -1, 160, 180]
