#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 24 12:44:13 2017

@author: brendontucker
"""
nums = [123456789, 836133896, 65475264, 836133896, 746254373, 1000000000, 
        542627588, 1000000000, 444088605, 65475264, 746254373, 542627588, 
        444088605]

#returns the number that only shows up one time        
def singleNumber(nums):
    counter = 0
    counted = 0
    while counter < len(nums):
        counted = nums.count(nums[counter])
        if counted == 1:
            return nums[counter]
        else:
            counter += 1
            
singleNumber(nums)