#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  8 14:01:21 2017

as much with regex as possible 
@author: brendontucker
"""


question = "questionword ,anotherquestionword,"

import re

chars = re.findall('[^?]+', question)
chars =  re.split(',', chars[0])
chars[0].title()
#chars2 = re.findall('[\S]+', question)
counter = 0
while counter < len(chars):
    chars[counter] = re.findall('[\S]+', chars[counter])
    counter = counter + 1


stringy = str()    
comma = ','
space = ' ' 

counter = 0
while counter < len(chars):#len(chars)
    counter2 = 0
    while counter2 < len(chars[counter]):
        if counter == 0 and counter2 == 0:
            chars[counter][counter2] = chars[counter][counter2].title()
            stringy = stringy + chars[counter][counter2]    
        elif counter == len(chars) - 1:
            stringy = stringy + ' ' + chars[counter][counter2]
        else:
            stringy = stringy + ' ' + chars[counter][counter2]
        
        counter2 = counter2 + 1
    if counter < len(chars) - 1:
        stringy = stringy + comma    
    counter = counter + 1

if stringy[-1] != ',':    
    stringy = stringy  + '?'
else:
    stringy = stringy + space + '?'

