#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  8 14:01:21 2017

as much with regex as possible 
@author: brendontucker
"""


question = "  Is,it    correct    ,    question?" #" this isn't a       relevant question , is it??? "

import re

chars = re.findall('[^?]+', question)
chars =  re.split(',', chars[0])
chars[0].title()
#chars2 = re.findall('[\S]+', question)
counter = 0
while counter < len(chars):
    chars[counter] = re.findall('[\S]+', chars[counter])
    counter = counter + 1


stringy = str()    

counter = 0
while counter < 1:#len(chars)
    if len(chars[counter]) < 1:
        stringy = stringy + chars[counter] #need to change for zeroth entry
        stringy = stringy + ','
        stringy = stringy + ' '
        counter = counter + 1
    else:
        counter2 = 0
        while counter2 < len(chars[counter]):
            stringy = stringy + chars[counter][counter2]
            counter2 = counter2 + 1
    counter = counter + 1
    
stringy = stringy  + '?'

