#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  8 14:01:21 2017

as much with regex as possible 
@author: brendontucker
"""


question = "  Is,it    correct    ,    question?" #" this isn't a       relevant question , is it??? "

import re

chars = re.findall('[^?]+', question)

chars2 = re.findall('[\S]+', chars[0])
'''
counter = 0
mark = list(chars[-1])
while counter < len(mark):
    if mark[counter] == '?':
        mark.remove(mark[counter])
        counter = counter
    else:
        counter = counter + 1

lastE = str()

counter = 0
while counter < len(mark):
    if counter == 0:
        lastE = mark[counter]
    else:
        lastE = lastE + mark[counter]
   
    counter = counter + 1

chars[-1] = lastE
        
chars[0] = chars[0].title()

answer = str()
counter = 0
while counter < len(chars):
    if chars[counter] == ',':
        
    elif counter == 0:
        answer = chars[counter]
    else:
        answer = answer + ' ' + chars[counter]

'''










'''
counter = 0
while counter < len(chars):
    mark = list(chars[counter])
    counter = counter + 1

counter = 0
counter2 = 0
while counter2 < len(mark):
    if '?' in 
while counter < len(mark):
    if mark[counter] == '?':
        mark.remove(mark[counter])
        counter = counter
    else:
        counter = counter + 1
        

'''

'''
mark = list(chars[-1])
while counter < len(mark):
    if mark[counter] == '?':
        mark.remove(mark[counter])
        counter = counter
    else:
        counter = counter + 1
'''