#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 25 13:48:52 2017

@author: brendontucker
"""
import collections
#nned to make some test data 
emails =["a@testz.com", "a@testz.com", "a@testb.com",
         "a@testb.com", "a@testc.com", "a@testc.com"]

def domainDictGenerator(emailList): 
 
    domainNameDict = dict()
    
    # just a tester line domainNameDict['@mit.edu'] = 1
    emailCounter = 0 
    while emailCounter < len(emailList) :
        backCounter = len(emailList[emailCounter]) - 1
        while backCounter > 0:
            if emails[emailCounter][backCounter] == '@':
                atLocation = backCounter
                domainName = emailList[emailCounter][atLocation + 1:len(emails[emailCounter])]
                if domainName in domainNameDict:
                    domainNameDict[domainName] += 20
                else:
                    domainNameDict[domainName] = 20
                break
            else:
                backCounter -= 1 
        emailCounter += 1
        
    return domainNameDict
    
#thedict = domainDictGenerator(emails)
#thedict['@new.dug'] = 303


def gigabyteConverter(thedict):

    for x in thedict:
        if thedict[x] > 500:
            thedict[x] = 25
        elif thedict[x] < 500 and thedict[x] >= 300 :
            thedict[x] = 15
        elif thedict[x] < 300 and thedict[x] >= 200 :
            thedict[x] = 8
        elif thedict[x] < 200 and thedict[x] >= 100 :
            thedict[x] = 3
        else:
            thedict[x] = 0
            
    return thedict
        
        
#tester = gigabyteConverter(domainDictGenerator(emails))

def campusCup(unOrderedDict):
    theDict = domainDictGenerator(unOrderedDict)
    convertedDict = gigabyteConverter(theDict)
    orderedTester = collections.OrderedDict(sorted(convertedDict.items()))
    keyList = []
    for x in orderedTester:
        keyList.append(x)
    valueList = []
    for x in orderedTester:
        valueList.append(orderedTester[x])
    
    outputList = []
    
    
    while len(valueList) > 0:
        temp = max(valueList)
        position = valueList.index(temp)
        outputList.append(keyList[position])
        valueList.pop(position)
        keyList.pop(position)
        
    return outputList
    
print(campusCup(emails))



#==============================================================================
#         
# orderedTester = collections.OrderedDict(sorted(tester.items()))
#     keyList = []
#     for x in orderedTester:
#         keyList.append(x)
#     valueList = []
#     for x in orderedTester:
#         valueList.append(orderedTester[x])
#     
#     outputList = []
#     
#     
#     while len(valueList) > 0:
#         temp = max(valueList)
#         position = valueList.index(temp)
#         outputList.append(keyList[position])
#         valueList.pop(position)
#         keyList.pop(position)
#==============================================================================
