#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  6 13:28:00 2017

@author: brendontucker
"""

attempts = ["1111", "4444",
            "9999", "3333",
             "2222",
            "7777", "0000",
            "6666", "7285",
            "5555", "1111"]
            
passcode = "1111"

def incorrectPasscodeAttempts(passcode, attempts):
    counter = 0
    boo = False
    
    for x in attempts:
        if x == passcode:
            counter = 0
        else:
            counter += 1
        if counter == 10:
            boo = True
            break
    return boo