#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  6 15:57:16 2017

@author: brendontucker
"""

inputString = "abacabadabacaba"
width = 7


counter = 0
result = None
window = None
backPos = 0

while counter < len(inputString):
    if counter == 0:
        result = inputString[0]
        counter += 1
    else:
        backPos = counter - width #should be proper width since Python is inclusive
        #at both ends with [] notation
        if backPos < 0:  
            backPos = 0
        counter += 1