#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 17 14:24:38 2017

@author: brendontucker
"""

n = 10

roads = [[1, 0], [1, 2], [8, 5], [9, 7], 
         [5, 6], [5, 4], [4, 6], [6, 7]]
         
indexedTimings = [[]for x in range(n)]
#for x in range(n): #take care of cities with no connections--isolated and removed step one
counter = 0

dayCounter = 0 #let this be the value that gets assinged 
while counter < n - 1:
    counter2 = 0
    while counter2 < n -1:
        if counter in roads[counter2]:
            
        else:
            counter2 = counter2 + 1
        
    #need a case for if the number isn't found, setting dayCounter = -1