#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  8 15:30:51 2016

@author: brendontucker
"""

n = 6
roads = [[3, 0], [0, 4], [5, 0], [2, 1],
          [1, 4], [2, 3], [5, 2]]

boo1 = False
list1 = list()
length = n - 1
counter1 = 0
while counter1 <= length:
    list1.append(counter1)
    counter1 = counter1 + 1

pos1 = 0
pos2 = 1
counter1 = 0
counter2 = 0
connectValue = None
connectList = list()

while counter2 <= length:
    while counter1 <= length:
        if roads[counter1][pos1] == counter2: 
            connectValue = roads[counter1][pos2]
            connectList.append(connectValue)
            counter1 = counter1 + 1
        elif roads[counter1][pos2] == counter2:
            connectValue = roads[counter1][pos1]
            connectList.append(connectValue)
            counter1 = counter1 + 1
        else:
            counter1 = counter1 + 1
    for x in connectList: 
        counter3 = 0
        counter4 = 0
        connectList = list()
        length2 = len(connectList)
        while counter3 <= length2:
            if roads[counter1][pos1] == connectList[counter3]: 
            connectValue = roads[counter1][pos2]
            connectList.append(connectValue)
            counter1 = counter1 + 1
        elif roads[counter1][pos2] == counter2:
            connectValue = roads[counter1][pos1]
            connectList.append(connectValue)
            counter1 = counter1 + 1
        else:
            counter1 = counter1 + 1
        
        #new connectList
        #if connectList2 + connectList 1 .sort =! list1
        #boo1 = False, break
        #else, clear both lists 
        #then add 1 to counter2 and do it all again
    counter2 = counter2 + 1
    #counter1 = 0 #could index connectList values and then do a boolean 
    #need something to store the list here
  