#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 12 10:56:53 2016

@author: brendontucker
"""
false = False
true = True
#listTry = list(list())

roadRegister = [[false, true,  true,  false],
                [true,  false, true,  false],
                [true,  true,  false, true ],
                [false, false, true,  false]]
                
choppedRR = [[] for x in range(len(roadRegister))]

counter = 0
counter2 = 0
appendPos = 0
#choppedRR[0].append(roadRegister[0][1:]) -- how to get proper position
   
while counter < len(roadRegister):#len(roadRegister)
    counter2 = 0 
    while counter2 < len(roadRegister):
        if counter2 == counter: #skip the row in question
                counter2 = counter2 + 1
            #elif zero case?
        else:
            extraPos = counter + 1
            temp = roadRegister[counter2][0:counter] + roadRegister[counter2][extraPos:]
            choppedRR[counter].append(temp)
            counter2 = counter2 + 1
    counter = counter + 1                

    

'''
while counter < len(roadRegister):#len(roadRegister)
    counter2 = 0 
    while counter2 < len(roadRegister):
        if counter == 0:
            extraPos = counter + 1
            temp = roadRegister[counter2][extraPos:]
            choppedRR[counter].append(temp)
            counter2 = counter2 + 1
        else:
            if counter2 == counter: #skip the row in question
                counter2 = counter2 + 1
            #elif zero case?
            else:
                extraPos = counter + 1
                temp = roadRegister[counter2][0:counter] + roadRegister[counter2][extraPos:]
                choppedRR[counter].append(temp)
                counter2 = counter2 + 1
    counter = counter + 1
''' 