#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  8 10:28:49 2016

@author: brendontucker
"""

import itertools 

cities = 4
roads = [[0, 1], [1, 2], [2, 0]]
cities = cities - 1
length = cities
citiesList = list()
while cities >= 0:
    citiesList.append(cities)
    cities = cities - 1

list1 = list(itertools.combinations(citiesList, 2))
length2 = len(list1)

pos1 = 0
big = 1
small = 0
while pos1 < length:
    if roads[pos1][0] > roads[pos1][1]:
        big = roads[pos1][0]
        small = roads[pos1][1]
        roads.remove(roads[pos1])
        roads.insert(pos1, [small, big])
        pos1 = pos1 + 1
    else:
        pos1 = pos1 + 1

pos1 = 0
while pos1 < length2:
    if list1[pos1][0] > list1[pos1][1]:
        big = list1[pos1][0]
        small = list1[pos1][1]
        list1.remove(list1[pos1])
        list1.insert(pos1, [small, big])
        pos1 = pos1 + 1
    else:
        pos1 = pos1 + 1

pos1 = 0
pos2 = 0
while pos2 < len(roads):
    pos1 = 0
    while pos1 < length2:
        if list1[pos1] == roads[pos2]:
            list1.remove(list1[pos1])
            length2 = len(list1)
            pos1 = pos1
        else:
            pos1 = pos1 + 1
    pos2 = pos2 + 1